### PR TITLE
Update class.ObjectIterator.inc.php

### PR DESCRIPTION
**Pull request by tm8544**
Prevent exception in creating RSS when there are no issues to publish

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for the pull request. 

You really should have forked from https://github.com/mantisbt/mantisbt and submitted the PR there, instead of using my personal development repo,

**Comment by tm8544** [comment]
Sorry about that, the link you gave me led me there

**Comment by dregad** [comment]
No problem, sorry for the confusion. That link was about the work-in-progress branch to replace the rssbuilder library.

**Comment by dregad** [comment]
Replaced by https://github.com/mantisbt/mantisbt/pull/1965

**Pull request closed without merging**
